// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, last_login_at, created_at
`

type CreateAccountParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.Email, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, username, email, password_hash, last_login_at, created_at FROM accounts WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, email, password_hash, last_login_at, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAccountLogin = `-- name: TouchAccountLogin :exec
UPDATE accounts SET last_login_at = $2 WHERE id = $1
`

type TouchAccountLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) TouchAccountLogin(ctx context.Context, arg TouchAccountLoginParams) error {
	_, err := q.db.Exec(ctx, touchAccountLogin, arg.ID, arg.LastLoginAt)
	return err
}
