// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alliance.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllianceMembers = `-- name: CountAllianceMembers :one
SELECT count(*) FROM alliance_members WHERE alliance_id = $1
`

func (q *Queries) CountAllianceMembers(ctx context.Context, allianceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAllianceMembers, allianceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAlliance = `-- name: DeleteAlliance :exec
DELETE FROM alliances WHERE id = $1
`

func (q *Queries) DeleteAlliance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlliance, id)
	return err
}

const deleteAllianceMember = `-- name: DeleteAllianceMember :exec
DELETE FROM alliance_members WHERE alliance_id = $1 AND player_id = $2
`

type DeleteAllianceMemberParams struct {
	AllianceID pgtype.UUID `json:"alliance_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
}

func (q *Queries) DeleteAllianceMember(ctx context.Context, arg DeleteAllianceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteAllianceMember, arg.AllianceID, arg.PlayerID)
	return err
}

const deleteJoinRequest = `-- name: DeleteJoinRequest :exec
DELETE FROM alliance_join_requests WHERE id = $1
`

func (q *Queries) DeleteJoinRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJoinRequest, id)
	return err
}

const deleteJoinRequestsByPlayer = `-- name: DeleteJoinRequestsByPlayer :exec
DELETE FROM alliance_join_requests WHERE player_id = $1
`

func (q *Queries) DeleteJoinRequestsByPlayer(ctx context.Context, playerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJoinRequestsByPlayer, playerID)
	return err
}

const getAlliance = `-- name: GetAlliance :one
SELECT id, world_id, name, tag, owner_player_id, entry_mode, member_cap, created_at FROM alliances WHERE id = $1
`

func (q *Queries) GetAlliance(ctx context.Context, id pgtype.UUID) (Alliance, error) {
	row := q.db.QueryRow(ctx, getAlliance, id)
	var i Alliance
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Name,
		&i.Tag,
		&i.OwnerPlayerID,
		&i.EntryMode,
		&i.MemberCap,
		&i.CreatedAt,
	)
	return i, err
}

const getAllianceForUpdate = `-- name: GetAllianceForUpdate :one
SELECT id, world_id, name, tag, owner_player_id, entry_mode, member_cap, created_at FROM alliances WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAllianceForUpdate(ctx context.Context, id pgtype.UUID) (Alliance, error) {
	row := q.db.QueryRow(ctx, getAllianceForUpdate, id)
	var i Alliance
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Name,
		&i.Tag,
		&i.OwnerPlayerID,
		&i.EntryMode,
		&i.MemberCap,
		&i.CreatedAt,
	)
	return i, err
}

const getAllianceMemberForUpdate = `-- name: GetAllianceMemberForUpdate :one
SELECT alliance_id, player_id, role, joined_at FROM alliance_members WHERE alliance_id = $1 AND player_id = $2 FOR UPDATE
`

type GetAllianceMemberForUpdateParams struct {
	AllianceID pgtype.UUID `json:"alliance_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
}

func (q *Queries) GetAllianceMemberForUpdate(ctx context.Context, arg GetAllianceMemberForUpdateParams) (AllianceMember, error) {
	row := q.db.QueryRow(ctx, getAllianceMemberForUpdate, arg.AllianceID, arg.PlayerID)
	var i AllianceMember
	err := row.Scan(
		&i.AllianceID,
		&i.PlayerID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT id, alliance_id, player_id, created_at FROM alliance_join_requests WHERE id = $1
`

func (q *Queries) GetJoinRequest(ctx context.Context, id pgtype.UUID) (AllianceJoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, id)
	var i AllianceJoinRequest
	err := row.Scan(
		&i.ID,
		&i.AllianceID,
		&i.PlayerID,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByPlayer = `-- name: GetMembershipByPlayer :one
SELECT alliance_id, player_id, role, joined_at FROM alliance_members WHERE player_id = $1
`

func (q *Queries) GetMembershipByPlayer(ctx context.Context, playerID pgtype.UUID) (AllianceMember, error) {
	row := q.db.QueryRow(ctx, getMembershipByPlayer, playerID)
	var i AllianceMember
	err := row.Scan(
		&i.AllianceID,
		&i.PlayerID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const insertAlliance = `-- name: InsertAlliance :one
INSERT INTO alliances (world_id, name, tag, owner_player_id, entry_mode)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, world_id, name, tag, owner_player_id, entry_mode, member_cap, created_at
`

type InsertAllianceParams struct {
	WorldID       pgtype.UUID `json:"world_id"`
	Name          string      `json:"name"`
	Tag           string      `json:"tag"`
	OwnerPlayerID pgtype.UUID `json:"owner_player_id"`
	EntryMode     string      `json:"entry_mode"`
}

func (q *Queries) InsertAlliance(ctx context.Context, arg InsertAllianceParams) (Alliance, error) {
	row := q.db.QueryRow(ctx, insertAlliance,
		arg.WorldID,
		arg.Name,
		arg.Tag,
		arg.OwnerPlayerID,
		arg.EntryMode,
	)
	var i Alliance
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Name,
		&i.Tag,
		&i.OwnerPlayerID,
		&i.EntryMode,
		&i.MemberCap,
		&i.CreatedAt,
	)
	return i, err
}

const insertAllianceMember = `-- name: InsertAllianceMember :exec
INSERT INTO alliance_members (alliance_id, player_id, role) VALUES ($1, $2, $3)
`

type InsertAllianceMemberParams struct {
	AllianceID pgtype.UUID `json:"alliance_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
	Role       string      `json:"role"`
}

func (q *Queries) InsertAllianceMember(ctx context.Context, arg InsertAllianceMemberParams) error {
	_, err := q.db.Exec(ctx, insertAllianceMember, arg.AllianceID, arg.PlayerID, arg.Role)
	return err
}

const insertJoinRequest = `-- name: InsertJoinRequest :exec
INSERT INTO alliance_join_requests (alliance_id, player_id) VALUES ($1, $2)
ON CONFLICT (alliance_id, player_id) DO NOTHING
`

type InsertJoinRequestParams struct {
	AllianceID pgtype.UUID `json:"alliance_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
}

func (q *Queries) InsertJoinRequest(ctx context.Context, arg InsertJoinRequestParams) error {
	_, err := q.db.Exec(ctx, insertJoinRequest, arg.AllianceID, arg.PlayerID)
	return err
}

const listAllianceMembers = `-- name: ListAllianceMembers :many
SELECT m.player_id, m.role, m.joined_at, p.username
FROM alliance_members m JOIN players p ON p.id = m.player_id
WHERE m.alliance_id = $1
ORDER BY m.joined_at
`

type ListAllianceMembersRow struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Role     string      `json:"role"`
	JoinedAt time.Time   `json:"joined_at"`
	Username string      `json:"username"`
}

func (q *Queries) ListAllianceMembers(ctx context.Context, allianceID pgtype.UUID) ([]ListAllianceMembersRow, error) {
	rows, err := q.db.Query(ctx, listAllianceMembers, allianceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllianceMembersRow
	for rows.Next() {
		var i ListAllianceMembersRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlliances = `-- name: ListAlliances :many
SELECT a.id, a.world_id, a.name, a.tag, a.owner_player_id, a.entry_mode, a.member_cap, a.created_at, count(m.player_id) AS members
FROM alliances a LEFT JOIN alliance_members m ON m.alliance_id = a.id
WHERE a.world_id = $1
GROUP BY a.id
ORDER BY members DESC, a.created_at
`

type ListAlliancesRow struct {
	ID            pgtype.UUID `json:"id"`
	WorldID       pgtype.UUID `json:"world_id"`
	Name          string      `json:"name"`
	Tag           string      `json:"tag"`
	OwnerPlayerID pgtype.UUID `json:"owner_player_id"`
	EntryMode     string      `json:"entry_mode"`
	MemberCap     int32       `json:"member_cap"`
	CreatedAt     time.Time   `json:"created_at"`
	Members       int64       `json:"members"`
}

func (q *Queries) ListAlliances(ctx context.Context, worldID pgtype.UUID) ([]ListAlliancesRow, error) {
	rows, err := q.db.Query(ctx, listAlliances, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlliancesRow
	for rows.Next() {
		var i ListAlliancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.Name,
			&i.Tag,
			&i.OwnerPlayerID,
			&i.EntryMode,
			&i.MemberCap,
			&i.CreatedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinRequests = `-- name: ListJoinRequests :many
SELECT r.id, r.player_id, r.created_at, p.username
FROM alliance_join_requests r JOIN players p ON p.id = r.player_id
WHERE r.alliance_id = $1
ORDER BY r.created_at
`

type ListJoinRequestsRow struct {
	ID        pgtype.UUID `json:"id"`
	PlayerID  pgtype.UUID `json:"player_id"`
	CreatedAt time.Time   `json:"created_at"`
	Username  string      `json:"username"`
}

func (q *Queries) ListJoinRequests(ctx context.Context, allianceID pgtype.UUID) ([]ListJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listJoinRequests, allianceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinRequestsRow
	for rows.Next() {
		var i ListJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAllianceEntryMode = `-- name: UpdateAllianceEntryMode :exec
UPDATE alliances SET entry_mode = $2 WHERE id = $1
`

type UpdateAllianceEntryModeParams struct {
	ID        pgtype.UUID `json:"id"`
	EntryMode string      `json:"entry_mode"`
}

func (q *Queries) UpdateAllianceEntryMode(ctx context.Context, arg UpdateAllianceEntryModeParams) error {
	_, err := q.db.Exec(ctx, updateAllianceEntryMode, arg.ID, arg.EntryMode)
	return err
}

const updateAllianceOwner = `-- name: UpdateAllianceOwner :exec
UPDATE alliances SET owner_player_id = $2 WHERE id = $1
`

type UpdateAllianceOwnerParams struct {
	ID            pgtype.UUID `json:"id"`
	OwnerPlayerID pgtype.UUID `json:"owner_player_id"`
}

func (q *Queries) UpdateAllianceOwner(ctx context.Context, arg UpdateAllianceOwnerParams) error {
	_, err := q.db.Exec(ctx, updateAllianceOwner, arg.ID, arg.OwnerPlayerID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE alliance_members SET role = $3 WHERE alliance_id = $1 AND player_id = $2
`

type UpdateMemberRoleParams struct {
	AllianceID pgtype.UUID `json:"alliance_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
	Role       string      `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.AllianceID, arg.PlayerID, arg.Role)
	return err
}
