// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveBattle = `-- name: GetActiveBattle :one
SELECT id, world_id, player_id, city_id, province_id, state, sent, status, created_at FROM battles WHERE city_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveBattle(ctx context.Context, cityID pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getActiveBattle, cityID)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.CityID,
		&i.ProvinceID,
		&i.State,
		&i.Sent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBattle = `-- name: GetBattle :one
SELECT id, world_id, player_id, city_id, province_id, state, sent, status, created_at FROM battles WHERE id = $1
`

func (q *Queries) GetBattle(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattle, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.CityID,
		&i.ProvinceID,
		&i.State,
		&i.Sent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBattleForUpdate = `-- name: GetBattleForUpdate :one
SELECT id, world_id, player_id, city_id, province_id, state, sent, status, created_at FROM battles WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBattleForUpdate(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattleForUpdate, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.CityID,
		&i.ProvinceID,
		&i.State,
		&i.Sent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertBattle = `-- name: InsertBattle :one
INSERT INTO battles (world_id, player_id, city_id, province_id, state, sent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, world_id, player_id, city_id, province_id, state, sent, status, created_at
`

type InsertBattleParams struct {
	WorldID    pgtype.UUID `json:"world_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
	CityID     pgtype.UUID `json:"city_id"`
	ProvinceID pgtype.UUID `json:"province_id"`
	State      []byte      `json:"state"`
	Sent       []byte      `json:"sent"`
}

func (q *Queries) InsertBattle(ctx context.Context, arg InsertBattleParams) (Battle, error) {
	row := q.db.QueryRow(ctx, insertBattle,
		arg.WorldID,
		arg.PlayerID,
		arg.CityID,
		arg.ProvinceID,
		arg.State,
		arg.Sent,
	)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.CityID,
		&i.ProvinceID,
		&i.State,
		&i.Sent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateBattleState = `-- name: UpdateBattleState :exec
UPDATE battles SET state = $2, status = $3 WHERE id = $1
`

type UpdateBattleStateParams struct {
	ID     pgtype.UUID `json:"id"`
	State  []byte      `json:"state"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBattleState(ctx context.Context, arg UpdateBattleStateParams) error {
	_, err := q.db.Exec(ctx, updateBattleState, arg.ID, arg.State, arg.Status)
	return err
}
