// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBuildQueue = `-- name: CancelBuildQueue :execrows
UPDATE build_queue SET status = 'cancelled'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelBuildQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBuildQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeBuildQueue = `-- name: CompleteBuildQueue :execrows
UPDATE build_queue SET status = 'completed'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CompleteBuildQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeBuildQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBuildQueueForUpdate = `-- name: GetBuildQueueForUpdate :one
SELECT id, city_id, building_id, building_type, target_level, pos_x, pos_y, started_at, finish_at, status, created_at FROM build_queue WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBuildQueueForUpdate(ctx context.Context, id pgtype.UUID) (BuildQueue, error) {
	row := q.db.QueryRow(ctx, getBuildQueueForUpdate, id)
	var i BuildQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.BuildingID,
		&i.BuildingType,
		&i.TargetLevel,
		&i.PosX,
		&i.PosY,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertBuildQueue = `-- name: InsertBuildQueue :one
INSERT INTO build_queue (city_id, building_id, building_type, target_level, pos_x, pos_y, started_at, finish_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, city_id, building_id, building_type, target_level, pos_x, pos_y, started_at, finish_at, status, created_at
`

type InsertBuildQueueParams struct {
	CityID       pgtype.UUID `json:"city_id"`
	BuildingID   pgtype.UUID `json:"building_id"`
	BuildingType string      `json:"building_type"`
	TargetLevel  int16       `json:"target_level"`
	PosX         int32       `json:"pos_x"`
	PosY         int32       `json:"pos_y"`
	StartedAt    time.Time   `json:"started_at"`
	FinishAt     time.Time   `json:"finish_at"`
}

func (q *Queries) InsertBuildQueue(ctx context.Context, arg InsertBuildQueueParams) (BuildQueue, error) {
	row := q.db.QueryRow(ctx, insertBuildQueue,
		arg.CityID,
		arg.BuildingID,
		arg.BuildingType,
		arg.TargetLevel,
		arg.PosX,
		arg.PosY,
		arg.StartedAt,
		arg.FinishAt,
	)
	var i BuildQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.BuildingID,
		&i.BuildingType,
		&i.TargetLevel,
		&i.PosX,
		&i.PosY,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingBuilds = `-- name: ListPendingBuilds :many
SELECT id, building_id, building_type, target_level, pos_x, pos_y, finish_at
FROM build_queue
WHERE city_id = $1 AND status = 'pending'
ORDER BY finish_at
`

type ListPendingBuildsRow struct {
	ID           pgtype.UUID `json:"id"`
	BuildingID   pgtype.UUID `json:"building_id"`
	BuildingType string      `json:"building_type"`
	TargetLevel  int16       `json:"target_level"`
	PosX         int32       `json:"pos_x"`
	PosY         int32       `json:"pos_y"`
	FinishAt     time.Time   `json:"finish_at"`
}

func (q *Queries) ListPendingBuilds(ctx context.Context, cityID pgtype.UUID) ([]ListPendingBuildsRow, error) {
	rows, err := q.db.Query(ctx, listPendingBuilds, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingBuildsRow
	for rows.Next() {
		var i ListPendingBuildsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.BuildingType,
			&i.TargetLevel,
			&i.PosX,
			&i.PosY,
			&i.FinishAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
