// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: build.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeBuildQueue = `-- name: CompleteBuildQueue :execrows
UPDATE build_queue SET status = 'completed'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CompleteBuildQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeBuildQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBuildQueueForUpdate = `-- name: GetBuildQueueForUpdate :one
SELECT id, city_id, slot_index, building_type, target_level, started_at, finish_at, status, created_at FROM build_queue WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBuildQueueForUpdate(ctx context.Context, id pgtype.UUID) (BuildQueue, error) {
	row := q.db.QueryRow(ctx, getBuildQueueForUpdate, id)
	var i BuildQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.SlotIndex,
		&i.BuildingType,
		&i.TargetLevel,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertBuildQueue = `-- name: InsertBuildQueue :one
INSERT INTO build_queue (city_id, slot_index, building_type, target_level, started_at, finish_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, city_id, slot_index, building_type, target_level, started_at, finish_at, status, created_at
`

type InsertBuildQueueParams struct {
	CityID       pgtype.UUID `json:"city_id"`
	SlotIndex    int16       `json:"slot_index"`
	BuildingType string      `json:"building_type"`
	TargetLevel  int16       `json:"target_level"`
	StartedAt    time.Time   `json:"started_at"`
	FinishAt     time.Time   `json:"finish_at"`
}

func (q *Queries) InsertBuildQueue(ctx context.Context, arg InsertBuildQueueParams) (BuildQueue, error) {
	row := q.db.QueryRow(ctx, insertBuildQueue,
		arg.CityID,
		arg.SlotIndex,
		arg.BuildingType,
		arg.TargetLevel,
		arg.StartedAt,
		arg.FinishAt,
	)
	var i BuildQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.SlotIndex,
		&i.BuildingType,
		&i.TargetLevel,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
