// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: city.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCityBuilding = `-- name: AddCityBuilding :one
INSERT INTO city_buildings (city_id, slot_index, building_type, level)
VALUES ($1, $2, $3, $4)
RETURNING city_id, slot_index, building_type, level
`

type AddCityBuildingParams struct {
	CityID       pgtype.UUID `json:"city_id"`
	SlotIndex    int16       `json:"slot_index"`
	BuildingType string      `json:"building_type"`
	Level        int16       `json:"level"`
}

func (q *Queries) AddCityBuilding(ctx context.Context, arg AddCityBuildingParams) (CityBuilding, error) {
	row := q.db.QueryRow(ctx, addCityBuilding,
		arg.CityID,
		arg.SlotIndex,
		arg.BuildingType,
		arg.Level,
	)
	var i CityBuilding
	err := row.Scan(
		&i.CityID,
		&i.SlotIndex,
		&i.BuildingType,
		&i.Level,
	)
	return i, err
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities (
    world_id, player_id, name, coord_x, coord_y, era,
    matter_stored, energy_stored, knowledge_stored,
    matter_rate, energy_rate, knowledge_rate,
    matter_cap, energy_cap, knowledge_cap,
    resources_updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16
)
RETURNING id, world_id, player_id, name, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at
`

type CreateCityParams struct {
	WorldID            pgtype.UUID `json:"world_id"`
	PlayerID           pgtype.UUID `json:"player_id"`
	Name               string      `json:"name"`
	CoordX             int32       `json:"coord_x"`
	CoordY             int32       `json:"coord_y"`
	Era                int16       `json:"era"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	MatterCap          float64     `json:"matter_cap"`
	EnergyCap          float64     `json:"energy_cap"`
	KnowledgeCap       float64     `json:"knowledge_cap"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.WorldID,
		arg.PlayerID,
		arg.Name,
		arg.CoordX,
		arg.CoordY,
		arg.Era,
		arg.MatterStored,
		arg.EnergyStored,
		arg.KnowledgeStored,
		arg.MatterRate,
		arg.EnergyRate,
		arg.KnowledgeRate,
		arg.MatterCap,
		arg.EnergyCap,
		arg.KnowledgeCap,
		arg.ResourcesUpdatedAt,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT id, world_id, player_id, name, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at FROM cities WHERE id = $1
`

func (q *Queries) GetCity(ctx context.Context, id pgtype.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCityBuildings = `-- name: ListCityBuildings :many
SELECT city_id, slot_index, building_type, level FROM city_buildings WHERE city_id = $1 ORDER BY slot_index
`

func (q *Queries) ListCityBuildings(ctx context.Context, cityID pgtype.UUID) ([]CityBuilding, error) {
	rows, err := q.db.Query(ctx, listCityBuildings, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityBuilding
	for rows.Next() {
		var i CityBuilding
		if err := rows.Scan(
			&i.CityID,
			&i.SlotIndex,
			&i.BuildingType,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCityResources = `-- name: UpdateCityResources :exec
UPDATE cities SET
    matter_stored = $2, energy_stored = $3, knowledge_stored = $4,
    matter_rate = $5, energy_rate = $6, knowledge_rate = $7,
    resources_updated_at = $8
WHERE id = $1
`

type UpdateCityResourcesParams struct {
	ID                 pgtype.UUID `json:"id"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
}

func (q *Queries) UpdateCityResources(ctx context.Context, arg UpdateCityResourcesParams) error {
	_, err := q.db.Exec(ctx, updateCityResources,
		arg.ID,
		arg.MatterStored,
		arg.EnergyStored,
		arg.KnowledgeStored,
		arg.MatterRate,
		arg.EnergyRate,
		arg.KnowledgeRate,
		arg.ResourcesUpdatedAt,
	)
	return err
}
