// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: city.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCityScouts = `-- name: AddCityScouts :exec
UPDATE cities SET scouts = scouts + $2 WHERE id = $1
`

type AddCityScoutsParams struct {
	ID     pgtype.UUID `json:"id"`
	Scouts int32       `json:"scouts"`
}

func (q *Queries) AddCityScouts(ctx context.Context, arg AddCityScoutsParams) error {
	_, err := q.db.Exec(ctx, addCityScouts, arg.ID, arg.Scouts)
	return err
}

const createCity = `-- name: CreateCity :one
INSERT INTO cities (
    world_id, player_id, name, region, coord_x, coord_y, era,
    matter_stored, energy_stored, knowledge_stored,
    matter_rate, energy_rate, knowledge_rate,
    matter_cap, energy_cap, knowledge_cap,
    resources_updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17
)
RETURNING id, world_id, player_id, name, region, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at, scouts
`

type CreateCityParams struct {
	WorldID            pgtype.UUID `json:"world_id"`
	PlayerID           pgtype.UUID `json:"player_id"`
	Name               string      `json:"name"`
	Region             string      `json:"region"`
	CoordX             int32       `json:"coord_x"`
	CoordY             int32       `json:"coord_y"`
	Era                int16       `json:"era"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	MatterCap          float64     `json:"matter_cap"`
	EnergyCap          float64     `json:"energy_cap"`
	KnowledgeCap       float64     `json:"knowledge_cap"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (City, error) {
	row := q.db.QueryRow(ctx, createCity,
		arg.WorldID,
		arg.PlayerID,
		arg.Name,
		arg.Region,
		arg.CoordX,
		arg.CoordY,
		arg.Era,
		arg.MatterStored,
		arg.EnergyStored,
		arg.KnowledgeStored,
		arg.MatterRate,
		arg.EnergyRate,
		arg.KnowledgeRate,
		arg.MatterCap,
		arg.EnergyCap,
		arg.KnowledgeCap,
		arg.ResourcesUpdatedAt,
	)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.Region,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
		&i.Scouts,
	)
	return i, err
}

const getCity = `-- name: GetCity :one
SELECT id, world_id, player_id, name, region, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at, scouts FROM cities WHERE id = $1
`

func (q *Queries) GetCity(ctx context.Context, id pgtype.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCity, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.Region,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
		&i.Scouts,
	)
	return i, err
}

const getCityAccountID = `-- name: GetCityAccountID :one
SELECT p.account_id FROM cities c JOIN players p ON p.id = c.player_id WHERE c.id = $1
`

func (q *Queries) GetCityAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCityAccountID, id)
	var account_id pgtype.UUID
	err := row.Scan(&account_id)
	return account_id, err
}

const getCityBuildingForUpdate = `-- name: GetCityBuildingForUpdate :one
SELECT id, city_id, building_type, level, pos_x, pos_y FROM city_buildings WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCityBuildingForUpdate(ctx context.Context, id pgtype.UUID) (CityBuilding, error) {
	row := q.db.QueryRow(ctx, getCityBuildingForUpdate, id)
	var i CityBuilding
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.BuildingType,
		&i.Level,
		&i.PosX,
		&i.PosY,
	)
	return i, err
}

const getCityByPlayer = `-- name: GetCityByPlayer :one
SELECT id, world_id, player_id, name, region, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at, scouts FROM cities WHERE player_id = $1
`

func (q *Queries) GetCityByPlayer(ctx context.Context, playerID pgtype.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCityByPlayer, playerID)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.Region,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
		&i.Scouts,
	)
	return i, err
}

const getCityForUpdate = `-- name: GetCityForUpdate :one
SELECT id, world_id, player_id, name, region, coord_x, coord_y, era, matter_stored, energy_stored, knowledge_stored, matter_rate, energy_rate, knowledge_rate, matter_cap, energy_cap, knowledge_cap, resources_updated_at, created_at, scouts FROM cities WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCityForUpdate(ctx context.Context, id pgtype.UUID) (City, error) {
	row := q.db.QueryRow(ctx, getCityForUpdate, id)
	var i City
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Name,
		&i.Region,
		&i.CoordX,
		&i.CoordY,
		&i.Era,
		&i.MatterStored,
		&i.EnergyStored,
		&i.KnowledgeStored,
		&i.MatterRate,
		&i.EnergyRate,
		&i.KnowledgeRate,
		&i.MatterCap,
		&i.EnergyCap,
		&i.KnowledgeCap,
		&i.ResourcesUpdatedAt,
		&i.CreatedAt,
		&i.Scouts,
	)
	return i, err
}

const insertCityBuilding = `-- name: InsertCityBuilding :one
INSERT INTO city_buildings (city_id, building_type, level, pos_x, pos_y)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, city_id, building_type, level, pos_x, pos_y
`

type InsertCityBuildingParams struct {
	CityID       pgtype.UUID `json:"city_id"`
	BuildingType string      `json:"building_type"`
	Level        int16       `json:"level"`
	PosX         int32       `json:"pos_x"`
	PosY         int32       `json:"pos_y"`
}

func (q *Queries) InsertCityBuilding(ctx context.Context, arg InsertCityBuildingParams) (CityBuilding, error) {
	row := q.db.QueryRow(ctx, insertCityBuilding,
		arg.CityID,
		arg.BuildingType,
		arg.Level,
		arg.PosX,
		arg.PosY,
	)
	var i CityBuilding
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.BuildingType,
		&i.Level,
		&i.PosX,
		&i.PosY,
	)
	return i, err
}

const listCityBuildings = `-- name: ListCityBuildings :many
SELECT id, city_id, building_type, level, pos_x, pos_y FROM city_buildings WHERE city_id = $1 ORDER BY pos_y, pos_x
`

func (q *Queries) ListCityBuildings(ctx context.Context, cityID pgtype.UUID) ([]CityBuilding, error) {
	rows, err := q.db.Query(ctx, listCityBuildings, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityBuilding
	for rows.Next() {
		var i CityBuilding
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.BuildingType,
			&i.Level,
			&i.PosX,
			&i.PosY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorldCities = `-- name: ListWorldCities :many
SELECT c.id, c.name, c.region, c.coord_x, c.coord_y, p.username,
       a.id AS alliance_id, a.tag AS alliance_tag
FROM cities c
JOIN players p ON p.id = c.player_id
LEFT JOIN alliance_members am ON am.player_id = p.id
LEFT JOIN alliances a ON a.id = am.alliance_id
WHERE c.world_id = $1
ORDER BY c.id
`

type ListWorldCitiesRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Region      string      `json:"region"`
	CoordX      int32       `json:"coord_x"`
	CoordY      int32       `json:"coord_y"`
	Username    string      `json:"username"`
	AllianceID  pgtype.UUID `json:"alliance_id"`
	AllianceTag *string     `json:"alliance_tag"`
}

func (q *Queries) ListWorldCities(ctx context.Context, worldID pgtype.UUID) ([]ListWorldCitiesRow, error) {
	rows, err := q.db.Query(ctx, listWorldCities, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorldCitiesRow
	for rows.Next() {
		var i ListWorldCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.CoordX,
			&i.CoordY,
			&i.Username,
			&i.AllianceID,
			&i.AllianceTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorldCityCoords = `-- name: ListWorldCityCoords :many
SELECT coord_x, coord_y FROM cities WHERE world_id = $1
`

type ListWorldCityCoordsRow struct {
	CoordX int32 `json:"coord_x"`
	CoordY int32 `json:"coord_y"`
}

func (q *Queries) ListWorldCityCoords(ctx context.Context, worldID pgtype.UUID) ([]ListWorldCityCoordsRow, error) {
	rows, err := q.db.Query(ctx, listWorldCityCoords, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorldCityCoordsRow
	for rows.Next() {
		var i ListWorldCityCoordsRow
		if err := rows.Scan(&i.CoordX, &i.CoordY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCityBuilding = `-- name: MoveCityBuilding :exec
UPDATE city_buildings SET pos_x = $2, pos_y = $3 WHERE id = $1
`

type MoveCityBuildingParams struct {
	ID   pgtype.UUID `json:"id"`
	PosX int32       `json:"pos_x"`
	PosY int32       `json:"pos_y"`
}

func (q *Queries) MoveCityBuilding(ctx context.Context, arg MoveCityBuildingParams) error {
	_, err := q.db.Exec(ctx, moveCityBuilding, arg.ID, arg.PosX, arg.PosY)
	return err
}

const setCityBuildingLevel = `-- name: SetCityBuildingLevel :exec
UPDATE city_buildings SET level = $2 WHERE id = $1
`

type SetCityBuildingLevelParams struct {
	ID    pgtype.UUID `json:"id"`
	Level int16       `json:"level"`
}

func (q *Queries) SetCityBuildingLevel(ctx context.Context, arg SetCityBuildingLevelParams) error {
	_, err := q.db.Exec(ctx, setCityBuildingLevel, arg.ID, arg.Level)
	return err
}

const updateCityResources = `-- name: UpdateCityResources :exec
UPDATE cities SET
    matter_stored = $2, energy_stored = $3, knowledge_stored = $4,
    matter_rate = $5, energy_rate = $6, knowledge_rate = $7,
    resources_updated_at = $8
WHERE id = $1
`

type UpdateCityResourcesParams struct {
	ID                 pgtype.UUID `json:"id"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
}

func (q *Queries) UpdateCityResources(ctx context.Context, arg UpdateCityResourcesParams) error {
	_, err := q.db.Exec(ctx, updateCityResources,
		arg.ID,
		arg.MatterStored,
		arg.EnergyStored,
		arg.KnowledgeStored,
		arg.MatterRate,
		arg.EnergyRate,
		arg.KnowledgeRate,
		arg.ResourcesUpdatedAt,
	)
	return err
}

const updateCityStorageCaps = `-- name: UpdateCityStorageCaps :exec
UPDATE cities SET
    matter_cap = $2, energy_cap = $3, knowledge_cap = $4
WHERE id = $1
`

type UpdateCityStorageCapsParams struct {
	ID           pgtype.UUID `json:"id"`
	MatterCap    float64     `json:"matter_cap"`
	EnergyCap    float64     `json:"energy_cap"`
	KnowledgeCap float64     `json:"knowledge_cap"`
}

func (q *Queries) UpdateCityStorageCaps(ctx context.Context, arg UpdateCityStorageCapsParams) error {
	_, err := q.db.Exec(ctx, updateCityStorageCaps,
		arg.ID,
		arg.MatterCap,
		arg.EnergyCap,
		arg.KnowledgeCap,
	)
	return err
}
