// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const duePendingEvents = `-- name: DuePendingEvents :many
SELECT id, world_id, type, fires_at, payload, status, created_at FROM scheduled_events
WHERE status = 'pending' AND fires_at <= $1
ORDER BY fires_at
`

func (q *Queries) DuePendingEvents(ctx context.Context, firesAt time.Time) ([]ScheduledEvent, error) {
	rows, err := q.db.Query(ctx, duePendingEvents, firesAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledEvent
	for rows.Next() {
		var i ScheduledEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.Type,
			&i.FiresAt,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScheduledEvent = `-- name: InsertScheduledEvent :one
INSERT INTO scheduled_events (type, fires_at, payload)
VALUES ($1, $2, $3)
RETURNING id, world_id, type, fires_at, payload, status, created_at
`

type InsertScheduledEventParams struct {
	Type    string    `json:"type"`
	FiresAt time.Time `json:"fires_at"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) InsertScheduledEvent(ctx context.Context, arg InsertScheduledEventParams) (ScheduledEvent, error) {
	row := q.db.QueryRow(ctx, insertScheduledEvent, arg.Type, arg.FiresAt, arg.Payload)
	var i ScheduledEvent
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Type,
		&i.FiresAt,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE scheduled_events SET status = 'processed' WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}
