// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: march.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMarchForUpdate = `-- name: GetMarchForUpdate :one
SELECT id, world_id, city_id, province_id, troops, survivors, attacker_won, status, depart_at, arrive_at, return_at, created_at FROM marches WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetMarchForUpdate(ctx context.Context, id pgtype.UUID) (March, error) {
	row := q.db.QueryRow(ctx, getMarchForUpdate, id)
	var i March
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.CityID,
		&i.ProvinceID,
		&i.Troops,
		&i.Survivors,
		&i.AttackerWon,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertMarch = `-- name: InsertMarch :one
INSERT INTO marches (world_id, city_id, province_id, troops, status, depart_at, arrive_at)
VALUES ($1, $2, $3, $4, 'outbound', $5, $6)
RETURNING id, world_id, city_id, province_id, troops, survivors, attacker_won, status, depart_at, arrive_at, return_at, created_at
`

type InsertMarchParams struct {
	WorldID    pgtype.UUID `json:"world_id"`
	CityID     pgtype.UUID `json:"city_id"`
	ProvinceID pgtype.UUID `json:"province_id"`
	Troops     []byte      `json:"troops"`
	DepartAt   time.Time   `json:"depart_at"`
	ArriveAt   time.Time   `json:"arrive_at"`
}

func (q *Queries) InsertMarch(ctx context.Context, arg InsertMarchParams) (March, error) {
	row := q.db.QueryRow(ctx, insertMarch,
		arg.WorldID,
		arg.CityID,
		arg.ProvinceID,
		arg.Troops,
		arg.DepartAt,
		arg.ArriveAt,
	)
	var i March
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.CityID,
		&i.ProvinceID,
		&i.Troops,
		&i.Survivors,
		&i.AttackerWon,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveMarches = `-- name: ListActiveMarches :many
SELECT id, world_id, city_id, province_id, troops, survivors, attacker_won, status, depart_at, arrive_at, return_at, created_at FROM marches WHERE city_id = $1 AND status <> 'done' ORDER BY arrive_at
`

func (q *Queries) ListActiveMarches(ctx context.Context, cityID pgtype.UUID) ([]March, error) {
	rows, err := q.db.Query(ctx, listActiveMarches, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []March
	for rows.Next() {
		var i March
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.CityID,
			&i.ProvinceID,
			&i.Troops,
			&i.Survivors,
			&i.AttackerWon,
			&i.Status,
			&i.DepartAt,
			&i.ArriveAt,
			&i.ReturnAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMarchDone = `-- name: SetMarchDone :exec
UPDATE marches SET status = 'done' WHERE id = $1
`

func (q *Queries) SetMarchDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setMarchDone, id)
	return err
}

const setMarchResult = `-- name: SetMarchResult :exec
UPDATE marches SET status = 'returning', attacker_won = $2, survivors = $3, return_at = $4 WHERE id = $1
`

type SetMarchResultParams struct {
	ID          pgtype.UUID        `json:"id"`
	AttackerWon *bool              `json:"attacker_won"`
	Survivors   []byte             `json:"survivors"`
	ReturnAt    pgtype.Timestamptz `json:"return_at"`
}

func (q *Queries) SetMarchResult(ctx context.Context, arg SetMarchResultParams) error {
	_, err := q.db.Exec(ctx, setMarchResult,
		arg.ID,
		arg.AttackerWon,
		arg.Survivors,
		arg.ReturnAt,
	)
	return err
}
