// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BuildQueue struct {
	ID           pgtype.UUID `json:"id"`
	CityID       pgtype.UUID `json:"city_id"`
	SlotIndex    int16       `json:"slot_index"`
	BuildingType string      `json:"building_type"`
	TargetLevel  int16       `json:"target_level"`
	StartedAt    time.Time   `json:"started_at"`
	FinishAt     time.Time   `json:"finish_at"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
}

type City struct {
	ID                 pgtype.UUID `json:"id"`
	WorldID            pgtype.UUID `json:"world_id"`
	PlayerID           pgtype.UUID `json:"player_id"`
	Name               string      `json:"name"`
	CoordX             int32       `json:"coord_x"`
	CoordY             int32       `json:"coord_y"`
	Era                int16       `json:"era"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	MatterCap          float64     `json:"matter_cap"`
	EnergyCap          float64     `json:"energy_cap"`
	KnowledgeCap       float64     `json:"knowledge_cap"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
	CreatedAt          time.Time   `json:"created_at"`
}

type CityBuilding struct {
	CityID       pgtype.UUID `json:"city_id"`
	SlotIndex    int16       `json:"slot_index"`
	BuildingType string      `json:"building_type"`
	Level        int16       `json:"level"`
}

type Player struct {
	ID           pgtype.UUID        `json:"id"`
	WorldID      pgtype.UUID        `json:"world_id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Faction      string             `json:"faction"`
	Era          int16              `json:"era"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ScheduledEvent struct {
	ID        pgtype.UUID `json:"id"`
	WorldID   pgtype.UUID `json:"world_id"`
	Type      string      `json:"type"`
	FiresAt   time.Time   `json:"fires_at"`
	Payload   []byte      `json:"payload"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type World struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Speed     int16              `json:"speed"`
	Status    string             `json:"status"`
	StartedAt time.Time          `json:"started_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt time.Time          `json:"created_at"`
}
