// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type Battle struct {
	ID         pgtype.UUID `json:"id"`
	WorldID    pgtype.UUID `json:"world_id"`
	PlayerID   pgtype.UUID `json:"player_id"`
	CityID     pgtype.UUID `json:"city_id"`
	ProvinceID pgtype.UUID `json:"province_id"`
	State      []byte      `json:"state"`
	Sent       []byte      `json:"sent"`
	Status     string      `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
}

type BuildQueue struct {
	ID           pgtype.UUID `json:"id"`
	CityID       pgtype.UUID `json:"city_id"`
	BuildingID   pgtype.UUID `json:"building_id"`
	BuildingType string      `json:"building_type"`
	TargetLevel  int16       `json:"target_level"`
	PosX         int32       `json:"pos_x"`
	PosY         int32       `json:"pos_y"`
	StartedAt    time.Time   `json:"started_at"`
	FinishAt     time.Time   `json:"finish_at"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
}

type City struct {
	ID                 pgtype.UUID `json:"id"`
	WorldID            pgtype.UUID `json:"world_id"`
	PlayerID           pgtype.UUID `json:"player_id"`
	Name               string      `json:"name"`
	Region             string      `json:"region"`
	CoordX             int32       `json:"coord_x"`
	CoordY             int32       `json:"coord_y"`
	Era                int16       `json:"era"`
	MatterStored       float64     `json:"matter_stored"`
	EnergyStored       float64     `json:"energy_stored"`
	KnowledgeStored    float64     `json:"knowledge_stored"`
	MatterRate         float64     `json:"matter_rate"`
	EnergyRate         float64     `json:"energy_rate"`
	KnowledgeRate      float64     `json:"knowledge_rate"`
	MatterCap          float64     `json:"matter_cap"`
	EnergyCap          float64     `json:"energy_cap"`
	KnowledgeCap       float64     `json:"knowledge_cap"`
	ResourcesUpdatedAt time.Time   `json:"resources_updated_at"`
	CreatedAt          time.Time   `json:"created_at"`
}

type CityBuilding struct {
	ID           pgtype.UUID `json:"id"`
	CityID       pgtype.UUID `json:"city_id"`
	BuildingType string      `json:"building_type"`
	Level        int16       `json:"level"`
	PosX         int32       `json:"pos_x"`
	PosY         int32       `json:"pos_y"`
}

type CityTroop struct {
	ID       pgtype.UUID `json:"id"`
	CityID   pgtype.UUID `json:"city_id"`
	UnitType string      `json:"unit_type"`
	Count    int32       `json:"count"`
}

type March struct {
	ID          pgtype.UUID        `json:"id"`
	WorldID     pgtype.UUID        `json:"world_id"`
	CityID      pgtype.UUID        `json:"city_id"`
	ProvinceID  pgtype.UUID        `json:"province_id"`
	Troops      []byte             `json:"troops"`
	Survivors   []byte             `json:"survivors"`
	AttackerWon *bool              `json:"attacker_won"`
	Status      string             `json:"status"`
	DepartAt    time.Time          `json:"depart_at"`
	ArriveAt    time.Time          `json:"arrive_at"`
	ReturnAt    pgtype.Timestamptz `json:"return_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Player struct {
	ID         pgtype.UUID        `json:"id"`
	WorldID    pgtype.UUID        `json:"world_id"`
	AccountID  pgtype.UUID        `json:"account_id"`
	Username   string             `json:"username"`
	Faction    string             `json:"faction"`
	Era        int16              `json:"era"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type Province struct {
	ID              pgtype.UUID        `json:"id"`
	WorldID         pgtype.UUID        `json:"world_id"`
	PlayerID        pgtype.UUID        `json:"player_id"`
	NameKey         string             `json:"name_key"`
	Q               int32              `json:"q"`
	R               int32              `json:"r"`
	Ring            int16              `json:"ring"`
	DefAttack       int32              `json:"def_attack"`
	DefHp           int32              `json:"def_hp"`
	RewardMatter    float64            `json:"reward_matter"`
	RewardEnergy    float64            `json:"reward_energy"`
	RewardKnowledge float64            `json:"reward_knowledge"`
	Status          string             `json:"status"`
	ConqueredAt     pgtype.Timestamptz `json:"conquered_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type RecruitQueue struct {
	ID        pgtype.UUID `json:"id"`
	CityID    pgtype.UUID `json:"city_id"`
	UnitType  string      `json:"unit_type"`
	Count     int32       `json:"count"`
	StartedAt time.Time   `json:"started_at"`
	FinishAt  time.Time   `json:"finish_at"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type Report struct {
	ID        pgtype.UUID `json:"id"`
	WorldID   pgtype.UUID `json:"world_id"`
	PlayerID  pgtype.UUID `json:"player_id"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
	Read      bool        `json:"read"`
	CreatedAt time.Time   `json:"created_at"`
}

type ScheduledEvent struct {
	ID        pgtype.UUID `json:"id"`
	WorldID   pgtype.UUID `json:"world_id"`
	Type      string      `json:"type"`
	FiresAt   time.Time   `json:"fires_at"`
	Payload   []byte      `json:"payload"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
}

type World struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Speed     int16              `json:"speed"`
	Status    string             `json:"status"`
	StartedAt time.Time          `json:"started_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt time.Time          `json:"created_at"`
}
