// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (world_id, username, email, password_hash, faction)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, world_id, username, email, password_hash, faction, era, last_seen_at, created_at
`

type CreatePlayerParams struct {
	WorldID      pgtype.UUID `json:"world_id"`
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Faction      string      `json:"faction"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.WorldID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Faction,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Faction,
		&i.Era,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, world_id, username, email, password_hash, faction, era, last_seen_at, created_at FROM players WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Faction,
		&i.Era,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
