// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: province.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayerProvinces = `-- name: CountPlayerProvinces :one
SELECT count(*) FROM provinces WHERE player_id = $1
`

func (q *Queries) CountPlayerProvinces(ctx context.Context, playerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerProvinces, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProvinceForUpdate = `-- name: GetProvinceForUpdate :one
SELECT id, world_id, player_id, name_key, q, r, ring, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, conquered_at, created_at FROM provinces WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetProvinceForUpdate(ctx context.Context, id pgtype.UUID) (Province, error) {
	row := q.db.QueryRow(ctx, getProvinceForUpdate, id)
	var i Province
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.NameKey,
		&i.Q,
		&i.R,
		&i.Ring,
		&i.DefAttack,
		&i.DefHp,
		&i.RewardMatter,
		&i.RewardEnergy,
		&i.RewardKnowledge,
		&i.Status,
		&i.ConqueredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertProvince = `-- name: InsertProvince :one
INSERT INTO provinces (world_id, player_id, name_key, q, r, ring, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, world_id, player_id, name_key, q, r, ring, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, conquered_at, created_at
`

type InsertProvinceParams struct {
	WorldID         pgtype.UUID `json:"world_id"`
	PlayerID        pgtype.UUID `json:"player_id"`
	NameKey         string      `json:"name_key"`
	Q               int32       `json:"q"`
	R               int32       `json:"r"`
	Ring            int16       `json:"ring"`
	DefAttack       int32       `json:"def_attack"`
	DefHp           int32       `json:"def_hp"`
	RewardMatter    float64     `json:"reward_matter"`
	RewardEnergy    float64     `json:"reward_energy"`
	RewardKnowledge float64     `json:"reward_knowledge"`
}

func (q *Queries) InsertProvince(ctx context.Context, arg InsertProvinceParams) (Province, error) {
	row := q.db.QueryRow(ctx, insertProvince,
		arg.WorldID,
		arg.PlayerID,
		arg.NameKey,
		arg.Q,
		arg.R,
		arg.Ring,
		arg.DefAttack,
		arg.DefHp,
		arg.RewardMatter,
		arg.RewardEnergy,
		arg.RewardKnowledge,
	)
	var i Province
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.NameKey,
		&i.Q,
		&i.R,
		&i.Ring,
		&i.DefAttack,
		&i.DefHp,
		&i.RewardMatter,
		&i.RewardEnergy,
		&i.RewardKnowledge,
		&i.Status,
		&i.ConqueredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayerProvinces = `-- name: ListPlayerProvinces :many
SELECT id, world_id, player_id, name_key, q, r, ring, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, conquered_at, created_at FROM provinces WHERE player_id = $1 ORDER BY ring, q, r
`

func (q *Queries) ListPlayerProvinces(ctx context.Context, playerID pgtype.UUID) ([]Province, error) {
	rows, err := q.db.Query(ctx, listPlayerProvinces, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Province
	for rows.Next() {
		var i Province
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.PlayerID,
			&i.NameKey,
			&i.Q,
			&i.R,
			&i.Ring,
			&i.DefAttack,
			&i.DefHp,
			&i.RewardMatter,
			&i.RewardEnergy,
			&i.RewardKnowledge,
			&i.Status,
			&i.ConqueredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProvinceConquered = `-- name: SetProvinceConquered :exec
UPDATE provinces SET status = 'conquered', conquered_at = $2 WHERE id = $1
`

type SetProvinceConqueredParams struct {
	ID          pgtype.UUID        `json:"id"`
	ConqueredAt pgtype.Timestamptz `json:"conquered_at"`
}

func (q *Queries) SetProvinceConquered(ctx context.Context, arg SetProvinceConqueredParams) error {
	_, err := q.db.Exec(ctx, setProvinceConquered, arg.ID, arg.ConqueredAt)
	return err
}
