// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCityBuilding(ctx context.Context, arg AddCityBuildingParams) (CityBuilding, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateWorld(ctx context.Context, arg CreateWorldParams) (World, error)
	GetCity(ctx context.Context, id pgtype.UUID) (City, error)
	GetPlayer(ctx context.Context, id pgtype.UUID) (Player, error)
	GetWorld(ctx context.Context, id pgtype.UUID) (World, error)
	ListCityBuildings(ctx context.Context, cityID pgtype.UUID) ([]CityBuilding, error)
	UpdateCityResources(ctx context.Context, arg UpdateCityResourcesParams) error
}

var _ Querier = (*Queries)(nil)
