// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCityScouts(ctx context.Context, arg AddCityScoutsParams) error
	AddCityTroops(ctx context.Context, arg AddCityTroopsParams) error
	CancelBuildQueue(ctx context.Context, id pgtype.UUID) (int64, error)
	CancelRecruitQueue(ctx context.Context, id pgtype.UUID) (int64, error)
	CompleteBuildQueue(ctx context.Context, id pgtype.UUID) (int64, error)
	CompleteRecruitQueue(ctx context.Context, id pgtype.UUID) (int64, error)
	CompleteScoutQueue(ctx context.Context, id pgtype.UUID) (int64, error)
	CountAliveWorldTargetsByKind(ctx context.Context, arg CountAliveWorldTargetsByKindParams) (int64, error)
	CountAllianceMembers(ctx context.Context, allianceID pgtype.UUID) (int64, error)
	CountPlayerProvinces(ctx context.Context, playerID pgtype.UUID) (int64, error)
	CountWorldTargets(ctx context.Context, worldID pgtype.UUID) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCity(ctx context.Context, arg CreateCityParams) (City, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateWorld(ctx context.Context, arg CreateWorldParams) (World, error)
	DeleteAccountSessions(ctx context.Context, accountID pgtype.UUID) error
	DeleteAlliance(ctx context.Context, id pgtype.UUID) error
	DeleteAllianceMember(ctx context.Context, arg DeleteAllianceMemberParams) error
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteJoinRequest(ctx context.Context, id pgtype.UUID) error
	DeleteJoinRequestsByPlayer(ctx context.Context, playerID pgtype.UUID) error
	DeleteSession(ctx context.Context, tokenHash string) error
	// Derruba o escudo de novato (ao fazer o 1º ataque).
	DropPlayerShield(ctx context.Context, id pgtype.UUID) error
	DuePendingEvents(ctx context.Context, firesAt time.Time) ([]ScheduledEvent, error)
	GetAccountByEmail(ctx context.Context, lower string) (Account, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error)
	GetActiveBattle(ctx context.Context, cityID pgtype.UUID) (Battle, error)
	GetAlliance(ctx context.Context, id pgtype.UUID) (Alliance, error)
	GetAllianceForUpdate(ctx context.Context, id pgtype.UUID) (Alliance, error)
	GetAllianceMemberForUpdate(ctx context.Context, arg GetAllianceMemberForUpdateParams) (AllianceMember, error)
	GetBattle(ctx context.Context, id pgtype.UUID) (Battle, error)
	GetBattleForUpdate(ctx context.Context, id pgtype.UUID) (Battle, error)
	GetBuildQueueForUpdate(ctx context.Context, id pgtype.UUID) (BuildQueue, error)
	GetCity(ctx context.Context, id pgtype.UUID) (City, error)
	GetCityAccountID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetCityBuildingForUpdate(ctx context.Context, id pgtype.UUID) (CityBuilding, error)
	GetCityByPlayer(ctx context.Context, playerID pgtype.UUID) (City, error)
	GetCityForUpdate(ctx context.Context, id pgtype.UUID) (City, error)
	GetJoinRequest(ctx context.Context, id pgtype.UUID) (AllianceJoinRequest, error)
	GetMarchForUpdate(ctx context.Context, id pgtype.UUID) (March, error)
	GetMembershipByPlayer(ctx context.Context, playerID pgtype.UUID) (AllianceMember, error)
	GetPlayer(ctx context.Context, id pgtype.UUID) (Player, error)
	GetPlayerByAccountAndWorld(ctx context.Context, arg GetPlayerByAccountAndWorldParams) (Player, error)
	GetPlayerForUpdate(ctx context.Context, id pgtype.UUID) (Player, error)
	GetProvinceForUpdate(ctx context.Context, id pgtype.UUID) (Province, error)
	GetRaidForUpdate(ctx context.Context, id pgtype.UUID) (Raid, error)
	GetRecruitForUpdate(ctx context.Context, id pgtype.UUID) (RecruitQueue, error)
	GetScoutMissionForUpdate(ctx context.Context, id pgtype.UUID) (ScoutMission, error)
	GetScoutQueueForUpdate(ctx context.Context, id pgtype.UUID) (ScoutQueue, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetWorld(ctx context.Context, id pgtype.UUID) (World, error)
	GetWorldForUpdate(ctx context.Context, id pgtype.UUID) (World, error)
	GetWorldMarchForUpdate(ctx context.Context, id pgtype.UUID) (WorldMarch, error)
	GetWorldTargetForUpdate(ctx context.Context, id pgtype.UUID) (WorldTarget, error)
	InsertAlliance(ctx context.Context, arg InsertAllianceParams) (Alliance, error)
	InsertAllianceMember(ctx context.Context, arg InsertAllianceMemberParams) error
	InsertBattle(ctx context.Context, arg InsertBattleParams) (Battle, error)
	InsertBuildQueue(ctx context.Context, arg InsertBuildQueueParams) (BuildQueue, error)
	InsertCityBuilding(ctx context.Context, arg InsertCityBuildingParams) (CityBuilding, error)
	InsertJoinRequest(ctx context.Context, arg InsertJoinRequestParams) error
	InsertMarch(ctx context.Context, arg InsertMarchParams) (March, error)
	InsertProvince(ctx context.Context, arg InsertProvinceParams) (Province, error)
	InsertRaid(ctx context.Context, arg InsertRaidParams) (Raid, error)
	InsertRecruitQueue(ctx context.Context, arg InsertRecruitQueueParams) (RecruitQueue, error)
	InsertReport(ctx context.Context, arg InsertReportParams) (Report, error)
	InsertScheduledEvent(ctx context.Context, arg InsertScheduledEventParams) (ScheduledEvent, error)
	InsertScoutMission(ctx context.Context, arg InsertScoutMissionParams) (ScoutMission, error)
	InsertScoutQueue(ctx context.Context, arg InsertScoutQueueParams) (ScoutQueue, error)
	InsertWorldMarch(ctx context.Context, arg InsertWorldMarchParams) (WorldMarch, error)
	InsertWorldTarget(ctx context.Context, arg InsertWorldTargetParams) (WorldTarget, error)
	ListActiveMarches(ctx context.Context, cityID pgtype.UUID) ([]March, error)
	ListActiveScoutMissions(ctx context.Context, attackerCityID pgtype.UUID) ([]ScoutMission, error)
	ListActiveWorldMarches(ctx context.Context, cityID pgtype.UUID) ([]WorldMarch, error)
	ListAllianceMembers(ctx context.Context, allianceID pgtype.UUID) ([]ListAllianceMembersRow, error)
	ListAlliances(ctx context.Context, worldID pgtype.UUID) ([]ListAlliancesRow, error)
	// Saques que SAÍRAM desta cidade (ataques em andamento).
	ListAttackerRaids(ctx context.Context, attackerCityID pgtype.UUID) ([]Raid, error)
	ListCityBuildings(ctx context.Context, cityID pgtype.UUID) ([]CityBuilding, error)
	ListCityTroops(ctx context.Context, cityID pgtype.UUID) ([]CityTroop, error)
	// Alvos de combate (village/creature) cujo TTL venceu E sem marcha a caminho (outbound trava o TTL).
	ListExpiredCombatTargets(ctx context.Context, arg ListExpiredCombatTargetsParams) ([]pgtype.UUID, error)
	// Saques VINDO para esta cidade (alerta de incoming — defesa ativa).
	ListIncomingRaids(ctx context.Context, defenderCityID pgtype.UUID) ([]Raid, error)
	ListJoinRequests(ctx context.Context, allianceID pgtype.UUID) ([]ListJoinRequestsRow, error)
	ListPendingBuilds(ctx context.Context, cityID pgtype.UUID) ([]ListPendingBuildsRow, error)
	ListPendingRecruits(ctx context.Context, cityID pgtype.UUID) ([]ListPendingRecruitsRow, error)
	ListPendingScouts(ctx context.Context, cityID pgtype.UUID) ([]ListPendingScoutsRow, error)
	ListPlayerProvinces(ctx context.Context, playerID pgtype.UUID) ([]Province, error)
	ListPlayerReports(ctx context.Context, playerID pgtype.UUID) ([]Report, error)
	ListWorldCities(ctx context.Context, worldID pgtype.UUID) ([]ListWorldCitiesRow, error)
	ListWorldCityCoords(ctx context.Context, worldID pgtype.UUID) ([]ListWorldCityCoordsRow, error)
	// Coords de TODOS os alvos (inclusive depletados) — para evitar colisão de posição ao spawnar.
	ListWorldTargetCoords(ctx context.Context, worldID pgtype.UUID) ([]ListWorldTargetCoordsRow, error)
	ListWorldTargets(ctx context.Context, worldID pgtype.UUID) ([]WorldTarget, error)
	MarkAllReportsRead(ctx context.Context, playerID pgtype.UUID) error
	MarkEventProcessed(ctx context.Context, id pgtype.UUID) error
	MoveCityBuilding(ctx context.Context, arg MoveCityBuildingParams) error
	// Libera a ocupação ao fim da coleta (nó ainda tem recurso).
	ReleaseWorldTarget(ctx context.Context, id pgtype.UUID) error
	// Reserva o nó para coleta: decrementa o restante e trava 1 ocupante (occupied_by = world_march).
	ReserveWorldTarget(ctx context.Context, arg ReserveWorldTargetParams) error
	// Nó zerou → respawna na MESMA linha em outro lugar (novas coords/nível/recurso/quantidade cheia).
	RespawnWorldTarget(ctx context.Context, arg RespawnWorldTargetParams) error
	SetCityBuildingLevel(ctx context.Context, arg SetCityBuildingLevelParams) error
	SetMarchDone(ctx context.Context, id pgtype.UUID) error
	SetMarchResult(ctx context.Context, arg SetMarchResultParams) error
	SetProvinceConquered(ctx context.Context, arg SetProvinceConqueredParams) error
	SetRaidDone(ctx context.Context, id pgtype.UUID) error
	SetRaidResult(ctx context.Context, arg SetRaidResultParams) error
	SetScoutMissionDone(ctx context.Context, id pgtype.UUID) error
	SetScoutMissionReturning(ctx context.Context, arg SetScoutMissionReturningParams) error
	SetWorldMarchCollecting(ctx context.Context, arg SetWorldMarchCollectingParams) error
	// Raid (village/creature): após o combate no destino, volta com sobreviventes + loot + resultado.
	SetWorldMarchCombatReturning(ctx context.Context, arg SetWorldMarchCombatReturningParams) error
	SetWorldMarchDone(ctx context.Context, id pgtype.UUID) error
	SetWorldMarchReturning(ctx context.Context, arg SetWorldMarchReturningParams) error
	// Marca o alvo como consumido/morto (combate vencido ou nó zerado sem respawn).
	SetWorldTargetDepleted(ctx context.Context, id pgtype.UUID) error
	// Gasta moeda premium de forma ATÔMICA: só debita se houver saldo (rows afetadas = 0 → sem saldo).
	SpendAccountPremium(ctx context.Context, arg SpendAccountPremiumParams) (int64, error)
	TouchAccountLogin(ctx context.Context, arg TouchAccountLoginParams) error
	UpdateAllianceEntryMode(ctx context.Context, arg UpdateAllianceEntryModeParams) error
	UpdateAllianceOwner(ctx context.Context, arg UpdateAllianceOwnerParams) error
	UpdateBattleState(ctx context.Context, arg UpdateBattleStateParams) error
	UpdateCityResources(ctx context.Context, arg UpdateCityResourcesParams) error
	UpdateCityStorageCaps(ctx context.Context, arg UpdateCityStorageCapsParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
}

var _ Querier = (*Queries)(nil)
