// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raid.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRaidForUpdate = `-- name: GetRaidForUpdate :one
SELECT id, world_id, attacker_city_id, defender_city_id, troops, survivors, attacker_won, loot, status, depart_at, arrive_at, return_at, created_at FROM raids WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRaidForUpdate(ctx context.Context, id pgtype.UUID) (Raid, error) {
	row := q.db.QueryRow(ctx, getRaidForUpdate, id)
	var i Raid
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.AttackerCityID,
		&i.DefenderCityID,
		&i.Troops,
		&i.Survivors,
		&i.AttackerWon,
		&i.Loot,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRaid = `-- name: InsertRaid :one
INSERT INTO raids (world_id, attacker_city_id, defender_city_id, troops, status, depart_at, arrive_at)
VALUES ($1, $2, $3, $4, 'outbound', $5, $6)
RETURNING id, world_id, attacker_city_id, defender_city_id, troops, survivors, attacker_won, loot, status, depart_at, arrive_at, return_at, created_at
`

type InsertRaidParams struct {
	WorldID        pgtype.UUID `json:"world_id"`
	AttackerCityID pgtype.UUID `json:"attacker_city_id"`
	DefenderCityID pgtype.UUID `json:"defender_city_id"`
	Troops         []byte      `json:"troops"`
	DepartAt       time.Time   `json:"depart_at"`
	ArriveAt       time.Time   `json:"arrive_at"`
}

func (q *Queries) InsertRaid(ctx context.Context, arg InsertRaidParams) (Raid, error) {
	row := q.db.QueryRow(ctx, insertRaid,
		arg.WorldID,
		arg.AttackerCityID,
		arg.DefenderCityID,
		arg.Troops,
		arg.DepartAt,
		arg.ArriveAt,
	)
	var i Raid
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.AttackerCityID,
		&i.DefenderCityID,
		&i.Troops,
		&i.Survivors,
		&i.AttackerWon,
		&i.Loot,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAttackerRaids = `-- name: ListAttackerRaids :many
SELECT id, world_id, attacker_city_id, defender_city_id, troops, survivors, attacker_won, loot, status, depart_at, arrive_at, return_at, created_at FROM raids WHERE attacker_city_id = $1 AND status <> 'done' ORDER BY arrive_at
`

// Saques que SAÍRAM desta cidade (ataques em andamento).
func (q *Queries) ListAttackerRaids(ctx context.Context, attackerCityID pgtype.UUID) ([]Raid, error) {
	rows, err := q.db.Query(ctx, listAttackerRaids, attackerCityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Raid
	for rows.Next() {
		var i Raid
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.AttackerCityID,
			&i.DefenderCityID,
			&i.Troops,
			&i.Survivors,
			&i.AttackerWon,
			&i.Loot,
			&i.Status,
			&i.DepartAt,
			&i.ArriveAt,
			&i.ReturnAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRaids = `-- name: ListIncomingRaids :many
SELECT id, world_id, attacker_city_id, defender_city_id, troops, survivors, attacker_won, loot, status, depart_at, arrive_at, return_at, created_at FROM raids WHERE defender_city_id = $1 AND status = 'outbound' ORDER BY arrive_at
`

// Saques VINDO para esta cidade (alerta de incoming — defesa ativa).
func (q *Queries) ListIncomingRaids(ctx context.Context, defenderCityID pgtype.UUID) ([]Raid, error) {
	rows, err := q.db.Query(ctx, listIncomingRaids, defenderCityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Raid
	for rows.Next() {
		var i Raid
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.AttackerCityID,
			&i.DefenderCityID,
			&i.Troops,
			&i.Survivors,
			&i.AttackerWon,
			&i.Loot,
			&i.Status,
			&i.DepartAt,
			&i.ArriveAt,
			&i.ReturnAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRaidDone = `-- name: SetRaidDone :exec
UPDATE raids SET status = 'done' WHERE id = $1
`

func (q *Queries) SetRaidDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setRaidDone, id)
	return err
}

const setRaidResult = `-- name: SetRaidResult :exec
UPDATE raids SET status = 'returning', attacker_won = $2, survivors = $3, loot = $4, return_at = $5 WHERE id = $1
`

type SetRaidResultParams struct {
	ID          pgtype.UUID        `json:"id"`
	AttackerWon *bool              `json:"attacker_won"`
	Survivors   []byte             `json:"survivors"`
	Loot        []byte             `json:"loot"`
	ReturnAt    pgtype.Timestamptz `json:"return_at"`
}

func (q *Queries) SetRaidResult(ctx context.Context, arg SetRaidResultParams) error {
	_, err := q.db.Exec(ctx, setRaidResult,
		arg.ID,
		arg.AttackerWon,
		arg.Survivors,
		arg.Loot,
		arg.ReturnAt,
	)
	return err
}
