// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (world_id, player_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, world_id, player_id, type, payload, read, created_at
`

type InsertReportParams struct {
	WorldID  pgtype.UUID `json:"world_id"`
	PlayerID pgtype.UUID `json:"player_id"`
	Type     string      `json:"type"`
	Payload  []byte      `json:"payload"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.WorldID,
		arg.PlayerID,
		arg.Type,
		arg.Payload,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.PlayerID,
		&i.Type,
		&i.Payload,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayerReports = `-- name: ListPlayerReports :many
SELECT id, world_id, player_id, type, payload, read, created_at FROM reports WHERE player_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListPlayerReports(ctx context.Context, playerID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listPlayerReports, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.PlayerID,
			&i.Type,
			&i.Payload,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllReportsRead = `-- name: MarkAllReportsRead :exec
UPDATE reports SET read = true WHERE player_id = $1 AND read = false
`

func (q *Queries) MarkAllReportsRead(ctx context.Context, playerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllReportsRead, playerID)
	return err
}
