// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scout.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeScoutQueue = `-- name: CompleteScoutQueue :execrows
UPDATE scout_queue SET status = 'completed' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CompleteScoutQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeScoutQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScoutMissionForUpdate = `-- name: GetScoutMissionForUpdate :one
SELECT id, world_id, attacker_city_id, target_city_id, status, intel, depart_at, arrive_at, return_at, created_at FROM scout_missions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetScoutMissionForUpdate(ctx context.Context, id pgtype.UUID) (ScoutMission, error) {
	row := q.db.QueryRow(ctx, getScoutMissionForUpdate, id)
	var i ScoutMission
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.AttackerCityID,
		&i.TargetCityID,
		&i.Status,
		&i.Intel,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScoutQueueForUpdate = `-- name: GetScoutQueueForUpdate :one
SELECT id, city_id, count, started_at, finish_at, status, created_at FROM scout_queue WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetScoutQueueForUpdate(ctx context.Context, id pgtype.UUID) (ScoutQueue, error) {
	row := q.db.QueryRow(ctx, getScoutQueueForUpdate, id)
	var i ScoutQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.Count,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertScoutMission = `-- name: InsertScoutMission :one
INSERT INTO scout_missions (world_id, attacker_city_id, target_city_id, status, depart_at, arrive_at)
VALUES ($1, $2, $3, 'outbound', $4, $5)
RETURNING id, world_id, attacker_city_id, target_city_id, status, intel, depart_at, arrive_at, return_at, created_at
`

type InsertScoutMissionParams struct {
	WorldID        pgtype.UUID `json:"world_id"`
	AttackerCityID pgtype.UUID `json:"attacker_city_id"`
	TargetCityID   pgtype.UUID `json:"target_city_id"`
	DepartAt       time.Time   `json:"depart_at"`
	ArriveAt       time.Time   `json:"arrive_at"`
}

func (q *Queries) InsertScoutMission(ctx context.Context, arg InsertScoutMissionParams) (ScoutMission, error) {
	row := q.db.QueryRow(ctx, insertScoutMission,
		arg.WorldID,
		arg.AttackerCityID,
		arg.TargetCityID,
		arg.DepartAt,
		arg.ArriveAt,
	)
	var i ScoutMission
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.AttackerCityID,
		&i.TargetCityID,
		&i.Status,
		&i.Intel,
		&i.DepartAt,
		&i.ArriveAt,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertScoutQueue = `-- name: InsertScoutQueue :one
INSERT INTO scout_queue (city_id, count, started_at, finish_at)
VALUES ($1, $2, $3, $4)
RETURNING id, city_id, count, started_at, finish_at, status, created_at
`

type InsertScoutQueueParams struct {
	CityID    pgtype.UUID `json:"city_id"`
	Count     int32       `json:"count"`
	StartedAt time.Time   `json:"started_at"`
	FinishAt  time.Time   `json:"finish_at"`
}

func (q *Queries) InsertScoutQueue(ctx context.Context, arg InsertScoutQueueParams) (ScoutQueue, error) {
	row := q.db.QueryRow(ctx, insertScoutQueue,
		arg.CityID,
		arg.Count,
		arg.StartedAt,
		arg.FinishAt,
	)
	var i ScoutQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.Count,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveScoutMissions = `-- name: ListActiveScoutMissions :many
SELECT id, world_id, attacker_city_id, target_city_id, status, intel, depart_at, arrive_at, return_at, created_at FROM scout_missions WHERE attacker_city_id = $1 AND status <> 'done' ORDER BY arrive_at
`

func (q *Queries) ListActiveScoutMissions(ctx context.Context, attackerCityID pgtype.UUID) ([]ScoutMission, error) {
	rows, err := q.db.Query(ctx, listActiveScoutMissions, attackerCityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScoutMission
	for rows.Next() {
		var i ScoutMission
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.AttackerCityID,
			&i.TargetCityID,
			&i.Status,
			&i.Intel,
			&i.DepartAt,
			&i.ArriveAt,
			&i.ReturnAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingScouts = `-- name: ListPendingScouts :many
SELECT id, count, finish_at FROM scout_queue WHERE city_id = $1 AND status = 'pending' ORDER BY finish_at
`

type ListPendingScoutsRow struct {
	ID       pgtype.UUID `json:"id"`
	Count    int32       `json:"count"`
	FinishAt time.Time   `json:"finish_at"`
}

func (q *Queries) ListPendingScouts(ctx context.Context, cityID pgtype.UUID) ([]ListPendingScoutsRow, error) {
	rows, err := q.db.Query(ctx, listPendingScouts, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingScoutsRow
	for rows.Next() {
		var i ListPendingScoutsRow
		if err := rows.Scan(&i.ID, &i.Count, &i.FinishAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScoutMissionDone = `-- name: SetScoutMissionDone :exec
UPDATE scout_missions SET status = 'done' WHERE id = $1
`

func (q *Queries) SetScoutMissionDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setScoutMissionDone, id)
	return err
}

const setScoutMissionReturning = `-- name: SetScoutMissionReturning :exec
UPDATE scout_missions SET status = 'returning', intel = $2, return_at = $3 WHERE id = $1
`

type SetScoutMissionReturningParams struct {
	ID       pgtype.UUID        `json:"id"`
	Intel    []byte             `json:"intel"`
	ReturnAt pgtype.Timestamptz `json:"return_at"`
}

func (q *Queries) SetScoutMissionReturning(ctx context.Context, arg SetScoutMissionReturningParams) error {
	_, err := q.db.Exec(ctx, setScoutMissionReturning, arg.ID, arg.Intel, arg.ReturnAt)
	return err
}
