// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: troop.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCityTroops = `-- name: AddCityTroops :exec
INSERT INTO city_troops (city_id, unit_type, count)
VALUES ($1, $2, $3)
ON CONFLICT (city_id, unit_type)
DO UPDATE SET count = city_troops.count + EXCLUDED.count
`

type AddCityTroopsParams struct {
	CityID   pgtype.UUID `json:"city_id"`
	UnitType string      `json:"unit_type"`
	Count    int32       `json:"count"`
}

func (q *Queries) AddCityTroops(ctx context.Context, arg AddCityTroopsParams) error {
	_, err := q.db.Exec(ctx, addCityTroops, arg.CityID, arg.UnitType, arg.Count)
	return err
}

const cancelRecruitQueue = `-- name: CancelRecruitQueue :execrows
UPDATE recruit_queue SET status = 'cancelled'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelRecruitQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRecruitQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeRecruitQueue = `-- name: CompleteRecruitQueue :execrows
UPDATE recruit_queue SET status = 'completed'
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CompleteRecruitQueue(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, completeRecruitQueue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecruitForUpdate = `-- name: GetRecruitForUpdate :one
SELECT id, city_id, unit_type, count, started_at, finish_at, status, created_at FROM recruit_queue WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetRecruitForUpdate(ctx context.Context, id pgtype.UUID) (RecruitQueue, error) {
	row := q.db.QueryRow(ctx, getRecruitForUpdate, id)
	var i RecruitQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.UnitType,
		&i.Count,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecruitQueue = `-- name: InsertRecruitQueue :one
INSERT INTO recruit_queue (city_id, unit_type, count, started_at, finish_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, city_id, unit_type, count, started_at, finish_at, status, created_at
`

type InsertRecruitQueueParams struct {
	CityID    pgtype.UUID `json:"city_id"`
	UnitType  string      `json:"unit_type"`
	Count     int32       `json:"count"`
	StartedAt time.Time   `json:"started_at"`
	FinishAt  time.Time   `json:"finish_at"`
}

func (q *Queries) InsertRecruitQueue(ctx context.Context, arg InsertRecruitQueueParams) (RecruitQueue, error) {
	row := q.db.QueryRow(ctx, insertRecruitQueue,
		arg.CityID,
		arg.UnitType,
		arg.Count,
		arg.StartedAt,
		arg.FinishAt,
	)
	var i RecruitQueue
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.UnitType,
		&i.Count,
		&i.StartedAt,
		&i.FinishAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCityTroops = `-- name: ListCityTroops :many
SELECT id, city_id, unit_type, count FROM city_troops WHERE city_id = $1 ORDER BY unit_type
`

func (q *Queries) ListCityTroops(ctx context.Context, cityID pgtype.UUID) ([]CityTroop, error) {
	rows, err := q.db.Query(ctx, listCityTroops, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityTroop
	for rows.Next() {
		var i CityTroop
		if err := rows.Scan(
			&i.ID,
			&i.CityID,
			&i.UnitType,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRecruits = `-- name: ListPendingRecruits :many
SELECT id, unit_type, count, finish_at
FROM recruit_queue
WHERE city_id = $1 AND status = 'pending'
ORDER BY finish_at
`

type ListPendingRecruitsRow struct {
	ID       pgtype.UUID `json:"id"`
	UnitType string      `json:"unit_type"`
	Count    int32       `json:"count"`
	FinishAt time.Time   `json:"finish_at"`
}

func (q *Queries) ListPendingRecruits(ctx context.Context, cityID pgtype.UUID) ([]ListPendingRecruitsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRecruits, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRecruitsRow
	for rows.Next() {
		var i ListPendingRecruitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitType,
			&i.Count,
			&i.FinishAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
