// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorld = `-- name: CreateWorld :one
INSERT INTO worlds (name, speed)
VALUES ($1, $2)
RETURNING id, name, speed, status, started_at, ends_at, created_at
`

type CreateWorldParams struct {
	Name  string `json:"name"`
	Speed int16  `json:"speed"`
}

func (q *Queries) CreateWorld(ctx context.Context, arg CreateWorldParams) (World, error) {
	row := q.db.QueryRow(ctx, createWorld, arg.Name, arg.Speed)
	var i World
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Speed,
		&i.Status,
		&i.StartedAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorld = `-- name: GetWorld :one
SELECT id, name, speed, status, started_at, ends_at, created_at FROM worlds WHERE id = $1
`

func (q *Queries) GetWorld(ctx context.Context, id pgtype.UUID) (World, error) {
	row := q.db.QueryRow(ctx, getWorld, id)
	var i World
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Speed,
		&i.Status,
		&i.StartedAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}
