// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_target.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorldTargets = `-- name: CountWorldTargets :one
SELECT count(*) FROM world_targets WHERE world_id = $1
`

func (q *Queries) CountWorldTargets(ctx context.Context, worldID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorldTargets, worldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorldTargetForUpdate = `-- name: GetWorldTargetForUpdate :one
SELECT id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, status, occupied_by, created_at FROM world_targets WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWorldTargetForUpdate(ctx context.Context, id pgtype.UUID) (WorldTarget, error) {
	row := q.db.QueryRow(ctx, getWorldTargetForUpdate, id)
	var i WorldTarget
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Kind,
		&i.Resource,
		&i.Level,
		&i.CoordX,
		&i.CoordY,
		&i.AmountTotal,
		&i.AmountRemaining,
		&i.Status,
		&i.OccupiedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorldTarget = `-- name: InsertWorldTarget :one
INSERT INTO world_targets (world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, status, occupied_by, created_at
`

type InsertWorldTargetParams struct {
	WorldID     pgtype.UUID `json:"world_id"`
	Kind        string      `json:"kind"`
	Resource    string      `json:"resource"`
	Level       int32       `json:"level"`
	CoordX      int32       `json:"coord_x"`
	CoordY      int32       `json:"coord_y"`
	AmountTotal float64     `json:"amount_total"`
}

func (q *Queries) InsertWorldTarget(ctx context.Context, arg InsertWorldTargetParams) (WorldTarget, error) {
	row := q.db.QueryRow(ctx, insertWorldTarget,
		arg.WorldID,
		arg.Kind,
		arg.Resource,
		arg.Level,
		arg.CoordX,
		arg.CoordY,
		arg.AmountTotal,
	)
	var i WorldTarget
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Kind,
		&i.Resource,
		&i.Level,
		&i.CoordX,
		&i.CoordY,
		&i.AmountTotal,
		&i.AmountRemaining,
		&i.Status,
		&i.OccupiedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listWorldTargets = `-- name: ListWorldTargets :many
SELECT id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, status, occupied_by, created_at FROM world_targets WHERE world_id = $1 AND status <> 'depleted' ORDER BY id
`

func (q *Queries) ListWorldTargets(ctx context.Context, worldID pgtype.UUID) ([]WorldTarget, error) {
	rows, err := q.db.Query(ctx, listWorldTargets, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldTarget
	for rows.Next() {
		var i WorldTarget
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.Kind,
			&i.Resource,
			&i.Level,
			&i.CoordX,
			&i.CoordY,
			&i.AmountTotal,
			&i.AmountRemaining,
			&i.Status,
			&i.OccupiedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseWorldTarget = `-- name: ReleaseWorldTarget :exec
UPDATE world_targets SET status = 'idle', occupied_by = NULL WHERE id = $1
`

// Libera a ocupação ao fim da coleta (nó ainda tem recurso).
func (q *Queries) ReleaseWorldTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseWorldTarget, id)
	return err
}

const reserveWorldTarget = `-- name: ReserveWorldTarget :exec
UPDATE world_targets SET amount_remaining = $2, status = 'occupied', occupied_by = $3 WHERE id = $1
`

type ReserveWorldTargetParams struct {
	ID              pgtype.UUID `json:"id"`
	AmountRemaining float64     `json:"amount_remaining"`
	OccupiedBy      pgtype.UUID `json:"occupied_by"`
}

// Reserva o nó para coleta: decrementa o restante e trava 1 ocupante (occupied_by = world_march).
func (q *Queries) ReserveWorldTarget(ctx context.Context, arg ReserveWorldTargetParams) error {
	_, err := q.db.Exec(ctx, reserveWorldTarget, arg.ID, arg.AmountRemaining, arg.OccupiedBy)
	return err
}

const respawnWorldTarget = `-- name: RespawnWorldTarget :exec
UPDATE world_targets SET kind = $2, resource = $3, level = $4, coord_x = $5, coord_y = $6,
    amount_total = $7, amount_remaining = $7, status = 'idle', occupied_by = NULL WHERE id = $1
`

type RespawnWorldTargetParams struct {
	ID          pgtype.UUID `json:"id"`
	Kind        string      `json:"kind"`
	Resource    string      `json:"resource"`
	Level       int32       `json:"level"`
	CoordX      int32       `json:"coord_x"`
	CoordY      int32       `json:"coord_y"`
	AmountTotal float64     `json:"amount_total"`
}

// Nó zerou → respawna na MESMA linha em outro lugar (novas coords/nível/recurso/quantidade cheia).
func (q *Queries) RespawnWorldTarget(ctx context.Context, arg RespawnWorldTargetParams) error {
	_, err := q.db.Exec(ctx, respawnWorldTarget,
		arg.ID,
		arg.Kind,
		arg.Resource,
		arg.Level,
		arg.CoordX,
		arg.CoordY,
		arg.AmountTotal,
	)
	return err
}
