// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_target.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAliveWorldTargetsByKind = `-- name: CountAliveWorldTargetsByKind :one
SELECT count(*) FROM world_targets WHERE world_id = $1 AND kind = $2 AND status <> 'depleted'
`

type CountAliveWorldTargetsByKindParams struct {
	WorldID pgtype.UUID `json:"world_id"`
	Kind    string      `json:"kind"`
}

func (q *Queries) CountAliveWorldTargetsByKind(ctx context.Context, arg CountAliveWorldTargetsByKindParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAliveWorldTargetsByKind, arg.WorldID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorldTargets = `-- name: CountWorldTargets :one
SELECT count(*) FROM world_targets WHERE world_id = $1
`

func (q *Queries) CountWorldTargets(ctx context.Context, worldID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorldTargets, worldID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorldTargetForUpdate = `-- name: GetWorldTargetForUpdate :one
SELECT id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, occupied_by, expires_at, created_at FROM world_targets WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWorldTargetForUpdate(ctx context.Context, id pgtype.UUID) (WorldTarget, error) {
	row := q.db.QueryRow(ctx, getWorldTargetForUpdate, id)
	var i WorldTarget
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Kind,
		&i.Resource,
		&i.Level,
		&i.CoordX,
		&i.CoordY,
		&i.AmountTotal,
		&i.AmountRemaining,
		&i.DefAttack,
		&i.DefHp,
		&i.RewardMatter,
		&i.RewardEnergy,
		&i.RewardKnowledge,
		&i.Status,
		&i.OccupiedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorldTarget = `-- name: InsertWorldTarget :one
INSERT INTO world_targets (world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining,
    def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, occupied_by, expires_at, created_at
`

type InsertWorldTargetParams struct {
	WorldID         pgtype.UUID        `json:"world_id"`
	Kind            string             `json:"kind"`
	Resource        string             `json:"resource"`
	Level           int32              `json:"level"`
	CoordX          int32              `json:"coord_x"`
	CoordY          int32              `json:"coord_y"`
	AmountTotal     float64            `json:"amount_total"`
	DefAttack       int32              `json:"def_attack"`
	DefHp           int32              `json:"def_hp"`
	RewardMatter    float64            `json:"reward_matter"`
	RewardEnergy    float64            `json:"reward_energy"`
	RewardKnowledge float64            `json:"reward_knowledge"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertWorldTarget(ctx context.Context, arg InsertWorldTargetParams) (WorldTarget, error) {
	row := q.db.QueryRow(ctx, insertWorldTarget,
		arg.WorldID,
		arg.Kind,
		arg.Resource,
		arg.Level,
		arg.CoordX,
		arg.CoordY,
		arg.AmountTotal,
		arg.DefAttack,
		arg.DefHp,
		arg.RewardMatter,
		arg.RewardEnergy,
		arg.RewardKnowledge,
		arg.ExpiresAt,
	)
	var i WorldTarget
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Kind,
		&i.Resource,
		&i.Level,
		&i.CoordX,
		&i.CoordY,
		&i.AmountTotal,
		&i.AmountRemaining,
		&i.DefAttack,
		&i.DefHp,
		&i.RewardMatter,
		&i.RewardEnergy,
		&i.RewardKnowledge,
		&i.Status,
		&i.OccupiedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredCombatTargets = `-- name: ListExpiredCombatTargets :many
SELECT id FROM world_targets t
WHERE t.world_id = $1 AND t.kind IN ('village', 'creature') AND t.status <> 'depleted'
  AND t.expires_at IS NOT NULL AND t.expires_at < $2
  AND NOT EXISTS (SELECT 1 FROM world_marches m WHERE m.target_id = t.id AND m.status = 'outbound')
`

type ListExpiredCombatTargetsParams struct {
	WorldID   pgtype.UUID        `json:"world_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Alvos de combate (village/creature) cujo TTL venceu E sem marcha a caminho (outbound trava o TTL).
func (q *Queries) ListExpiredCombatTargets(ctx context.Context, arg ListExpiredCombatTargetsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredCombatTargets, arg.WorldID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorldTargetCoords = `-- name: ListWorldTargetCoords :many
SELECT coord_x, coord_y FROM world_targets WHERE world_id = $1
`

type ListWorldTargetCoordsRow struct {
	CoordX int32 `json:"coord_x"`
	CoordY int32 `json:"coord_y"`
}

// Coords de TODOS os alvos (inclusive depletados) — para evitar colisão de posição ao spawnar.
func (q *Queries) ListWorldTargetCoords(ctx context.Context, worldID pgtype.UUID) ([]ListWorldTargetCoordsRow, error) {
	rows, err := q.db.Query(ctx, listWorldTargetCoords, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorldTargetCoordsRow
	for rows.Next() {
		var i ListWorldTargetCoordsRow
		if err := rows.Scan(&i.CoordX, &i.CoordY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorldTargets = `-- name: ListWorldTargets :many
SELECT id, world_id, kind, resource, level, coord_x, coord_y, amount_total, amount_remaining, def_attack, def_hp, reward_matter, reward_energy, reward_knowledge, status, occupied_by, expires_at, created_at FROM world_targets WHERE world_id = $1 AND status <> 'depleted' ORDER BY id
`

func (q *Queries) ListWorldTargets(ctx context.Context, worldID pgtype.UUID) ([]WorldTarget, error) {
	rows, err := q.db.Query(ctx, listWorldTargets, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldTarget
	for rows.Next() {
		var i WorldTarget
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.Kind,
			&i.Resource,
			&i.Level,
			&i.CoordX,
			&i.CoordY,
			&i.AmountTotal,
			&i.AmountRemaining,
			&i.DefAttack,
			&i.DefHp,
			&i.RewardMatter,
			&i.RewardEnergy,
			&i.RewardKnowledge,
			&i.Status,
			&i.OccupiedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseWorldTarget = `-- name: ReleaseWorldTarget :exec
UPDATE world_targets SET status = 'idle', occupied_by = NULL WHERE id = $1
`

// Libera a ocupação ao fim da coleta (nó ainda tem recurso).
func (q *Queries) ReleaseWorldTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseWorldTarget, id)
	return err
}

const reserveWorldTarget = `-- name: ReserveWorldTarget :exec
UPDATE world_targets SET amount_remaining = $2, status = 'occupied', occupied_by = $3 WHERE id = $1
`

type ReserveWorldTargetParams struct {
	ID              pgtype.UUID `json:"id"`
	AmountRemaining float64     `json:"amount_remaining"`
	OccupiedBy      pgtype.UUID `json:"occupied_by"`
}

// Reserva o nó para coleta: decrementa o restante e trava 1 ocupante (occupied_by = world_march).
func (q *Queries) ReserveWorldTarget(ctx context.Context, arg ReserveWorldTargetParams) error {
	_, err := q.db.Exec(ctx, reserveWorldTarget, arg.ID, arg.AmountRemaining, arg.OccupiedBy)
	return err
}

const respawnWorldTarget = `-- name: RespawnWorldTarget :exec
UPDATE world_targets SET kind = $2, resource = $3, level = $4, coord_x = $5, coord_y = $6,
    amount_total = $7, amount_remaining = $7, status = 'idle', occupied_by = NULL WHERE id = $1
`

type RespawnWorldTargetParams struct {
	ID          pgtype.UUID `json:"id"`
	Kind        string      `json:"kind"`
	Resource    string      `json:"resource"`
	Level       int32       `json:"level"`
	CoordX      int32       `json:"coord_x"`
	CoordY      int32       `json:"coord_y"`
	AmountTotal float64     `json:"amount_total"`
}

// Nó zerou → respawna na MESMA linha em outro lugar (novas coords/nível/recurso/quantidade cheia).
func (q *Queries) RespawnWorldTarget(ctx context.Context, arg RespawnWorldTargetParams) error {
	_, err := q.db.Exec(ctx, respawnWorldTarget,
		arg.ID,
		arg.Kind,
		arg.Resource,
		arg.Level,
		arg.CoordX,
		arg.CoordY,
		arg.AmountTotal,
	)
	return err
}

const setWorldTargetDepleted = `-- name: SetWorldTargetDepleted :exec
UPDATE world_targets SET status = 'depleted', occupied_by = NULL WHERE id = $1
`

// Marca o alvo como consumido/morto (combate vencido ou nó zerado sem respawn).
func (q *Queries) SetWorldTargetDepleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setWorldTargetDepleted, id)
	return err
}
