// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world_march.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorldMarchForUpdate = `-- name: GetWorldMarchForUpdate :one
SELECT id, world_id, city_id, target_id, troops, survivors, loot, attacker_won, status, depart_at, arrive_at, collect_until, return_at, created_at FROM world_marches WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWorldMarchForUpdate(ctx context.Context, id pgtype.UUID) (WorldMarch, error) {
	row := q.db.QueryRow(ctx, getWorldMarchForUpdate, id)
	var i WorldMarch
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.CityID,
		&i.TargetID,
		&i.Troops,
		&i.Survivors,
		&i.Loot,
		&i.AttackerWon,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.CollectUntil,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorldMarch = `-- name: InsertWorldMarch :one
INSERT INTO world_marches (world_id, city_id, target_id, troops, status, depart_at, arrive_at)
VALUES ($1, $2, $3, $4, 'outbound', $5, $6)
RETURNING id, world_id, city_id, target_id, troops, survivors, loot, attacker_won, status, depart_at, arrive_at, collect_until, return_at, created_at
`

type InsertWorldMarchParams struct {
	WorldID  pgtype.UUID `json:"world_id"`
	CityID   pgtype.UUID `json:"city_id"`
	TargetID pgtype.UUID `json:"target_id"`
	Troops   []byte      `json:"troops"`
	DepartAt time.Time   `json:"depart_at"`
	ArriveAt time.Time   `json:"arrive_at"`
}

func (q *Queries) InsertWorldMarch(ctx context.Context, arg InsertWorldMarchParams) (WorldMarch, error) {
	row := q.db.QueryRow(ctx, insertWorldMarch,
		arg.WorldID,
		arg.CityID,
		arg.TargetID,
		arg.Troops,
		arg.DepartAt,
		arg.ArriveAt,
	)
	var i WorldMarch
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.CityID,
		&i.TargetID,
		&i.Troops,
		&i.Survivors,
		&i.Loot,
		&i.AttackerWon,
		&i.Status,
		&i.DepartAt,
		&i.ArriveAt,
		&i.CollectUntil,
		&i.ReturnAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWorldMarches = `-- name: ListActiveWorldMarches :many
SELECT id, world_id, city_id, target_id, troops, survivors, loot, attacker_won, status, depart_at, arrive_at, collect_until, return_at, created_at FROM world_marches WHERE city_id = $1 AND status <> 'done' ORDER BY arrive_at
`

func (q *Queries) ListActiveWorldMarches(ctx context.Context, cityID pgtype.UUID) ([]WorldMarch, error) {
	rows, err := q.db.Query(ctx, listActiveWorldMarches, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorldMarch
	for rows.Next() {
		var i WorldMarch
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.CityID,
			&i.TargetID,
			&i.Troops,
			&i.Survivors,
			&i.Loot,
			&i.AttackerWon,
			&i.Status,
			&i.DepartAt,
			&i.ArriveAt,
			&i.CollectUntil,
			&i.ReturnAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorldMarchCollecting = `-- name: SetWorldMarchCollecting :exec
UPDATE world_marches SET status = 'collecting', loot = $2, collect_until = $3 WHERE id = $1
`

type SetWorldMarchCollectingParams struct {
	ID           pgtype.UUID        `json:"id"`
	Loot         []byte             `json:"loot"`
	CollectUntil pgtype.Timestamptz `json:"collect_until"`
}

func (q *Queries) SetWorldMarchCollecting(ctx context.Context, arg SetWorldMarchCollectingParams) error {
	_, err := q.db.Exec(ctx, setWorldMarchCollecting, arg.ID, arg.Loot, arg.CollectUntil)
	return err
}

const setWorldMarchCombatReturning = `-- name: SetWorldMarchCombatReturning :exec
UPDATE world_marches SET status = 'returning', survivors = $2, loot = $3, attacker_won = $4, return_at = $5 WHERE id = $1
`

type SetWorldMarchCombatReturningParams struct {
	ID          pgtype.UUID        `json:"id"`
	Survivors   []byte             `json:"survivors"`
	Loot        []byte             `json:"loot"`
	AttackerWon *bool              `json:"attacker_won"`
	ReturnAt    pgtype.Timestamptz `json:"return_at"`
}

// Raid (village/creature): após o combate no destino, volta com sobreviventes + loot + resultado.
func (q *Queries) SetWorldMarchCombatReturning(ctx context.Context, arg SetWorldMarchCombatReturningParams) error {
	_, err := q.db.Exec(ctx, setWorldMarchCombatReturning,
		arg.ID,
		arg.Survivors,
		arg.Loot,
		arg.AttackerWon,
		arg.ReturnAt,
	)
	return err
}

const setWorldMarchDone = `-- name: SetWorldMarchDone :exec
UPDATE world_marches SET status = 'done' WHERE id = $1
`

func (q *Queries) SetWorldMarchDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setWorldMarchDone, id)
	return err
}

const setWorldMarchReturning = `-- name: SetWorldMarchReturning :exec
UPDATE world_marches SET status = 'returning', survivors = $2, return_at = $3 WHERE id = $1
`

type SetWorldMarchReturningParams struct {
	ID        pgtype.UUID        `json:"id"`
	Survivors []byte             `json:"survivors"`
	ReturnAt  pgtype.Timestamptz `json:"return_at"`
}

func (q *Queries) SetWorldMarchReturning(ctx context.Context, arg SetWorldMarchReturningParams) error {
	_, err := q.db.Exec(ctx, setWorldMarchReturning, arg.ID, arg.Survivors, arg.ReturnAt)
	return err
}
